name: flutter_sqlite_document_search
description: SQLIte AI Document Explorer
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  drift: ^2.19.1+1
  drift_flutter: ^0.1.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3 
  mediapipe_core: ^0.0.1
  mediapipe_text: ^0.0.1
  html: ^0.15.4
  markdown: ^7.2.2
  path: ^1.9.0
  path_provider: ^2.1.4
  signals: ^5.3.0
  sqlite3: ^2.4.5
  sqlite3_flutter_libs: ^0.5.24
  sqlite_vec:
    path: third_party/sqlite-vec/bindings/dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.19.1
  build_runner: ^2.4.11
  build: ^2.4.1
  build_web_compilers: ^4.0.10

flutter:
  uses-material-design: true
  assets:
    - assets/universal-sentence-encoder.tflite